import { useState } from 'react';
import { get, post, upload, download, setToken } from './api';
import './workbench.css';
const STAGES = ['DATA RECEIVED', 'VALIDATION', 'SIGNAL/SYSTEM MAPPING', 'ANALYSIS', 'RESULTS', 'EVIDENCE', 'CUSTOMER REPORT'];
const EMPTY = { context: '', start: '', end: '', signals: [], pair_confirmed: false };
const Json = ({ value }) => <pre>{JSON.stringify(value, null, 2)}</pre>;
export default function App() {
  const [token, editToken] = useState(''), [connected, setConnected] = useState(false);
  const [items, setItems] = useState([]), [evaluation, setEvaluation] = useState(null), [authority, setAuthority] = useState(null);
  const [busy, setBusy] = useState(''), [error, setError] = useState('');
  const [time, setTime] = useState({ timestamp_column: '', timestamp_mode: 'iso' });
  const [mapping, setMapping] = useState(EMPTY), [preview, setPreview] = useState(null), [approved, setApproved] = useState(false);
  const [run, setRun] = useState(null), [review, setReview] = useState(null), [reviewer, setReviewer] = useState(''), [reviewed, setReviewed] = useState(false);
  const [referenceTime, setReferenceTime] = useState({ timestamp_column: '', timestamp_mode: 'iso' });
  const [create, setCreate] = useState({ mode: 'single', customer: '', facility: '', system: '', scope: '' });
  async function act(label, fn) {
    setBusy(label); setError('');
    try { await fn(); } catch(e) { setError(typeof e.response?.data?.detail === 'string' ? e.response.data.detail : e.message); }
    finally { setBusy(''); }
  }
  async function refresh(id) {
    const [list, item] = await Promise.all([get('/evaluations'), get(`/evaluations/${id}`)]);
    setItems(list); setEvaluation(item); return item;
  }
  async function select(id) {
    setRun(null); setReview(null); setReviewed(false);
    const item = await refresh(id);
    setReferenceTime(item.reference_validation ? { timestamp_column: item.reference_validation.timestamp_column, timestamp_mode: item.reference_validation.timestamp_mode } : { timestamp_column: '', timestamp_mode: 'iso' });
    setTime({ timestamp_column: item.validation?.timestamp_column || '', timestamp_mode: item.validation?.timestamp_mode || 'iso' });
    setMapping(item.mapping || { ...EMPTY, signals: (item.validation?.signals || []).map(s => ({ column: s.column, include: false, meaning: '', unit: '', reason: '' })) }); setPreview(item.preview || null); setApproved(!!item.approved_mapping);
  }
  function edit(next) { setMapping(next); setPreview(null); setApproved(false); }
  function editSignal(i, field, value) { edit({ ...mapping, signals: mapping.signals.map((s, j) => i === j ? { ...s, [field]: value } : s) }); }
  const root = `/evaluations/${evaluation?.id}`;
  const action = (label, fn, disabled = false) => <button disabled={!!busy || disabled} onClick={() => act(label, fn)}>{label}</button>;
  return <div className="workbench">
    <header><span className="eyebrow">NERAIUM · INTERNAL</span><h1>Historical evaluation workbench</h1><p>Supplied telemetry → defensible evidence</p></header>
    <p>Read-only historical evaluation for Neraium staff. No live monitoring or equipment control.</p>
    {error && <div className="error" role="alert">{error}</div>}{busy && <p role="status" className="notice">{busy}…</p>}
    {!connected ? <form className="panel narrow" onSubmit={e => { e.preventDefault(); act('Opening workbench', async () => {
      setToken(token); const [list, state] = await Promise.all([get('/evaluations'), get('/authority')]);
      setItems(list); setAuthority(state); setConnected(true); editToken('');
    }); }}><h2>Analyst access</h2><label>Internal workbench token<input type="password" autoComplete="off" required value={token} onChange={e => editToken(e.target.value)} /></label><button disabled={!!busy}>Open workbench</button><p>Token held only in this tab's memory.</p></form> : <>
    <fieldset disabled={!!busy}><p className={authority?.available ? 'notice' : 'error'}>Authority: {authority?.available ? `Neraium-1.0 ${authority.identity.commit.slice(0, 12)}` : authority?.reason}</p>
    <div className="layout"><aside><section className="panel"><h2>Evaluations</h2><label>Select evaluation<select disabled={!!busy} value={evaluation?.id || ''} onChange={e => e.target.value && act('Loading evaluation', () => select(e.target.value))}><option value="">Choose…</option>{items.map(e => <option key={e.id} value={e.id}>{e.customer} · {e.system}</option>)}</select></label>
    <details><summary>Create evaluation</summary><form onSubmit={e => { e.preventDefault(); act('Creating evaluation', async () => { const item = await post('/evaluations', create); await select(item.id); }); }}>
      <label>Evaluation mode<select value={create.mode} onChange={e => setCreate({ ...create, mode: e.target.value })}><option value="single">Single dataset</option><option value="paired">Paired reference / comparison</option></select></label>
      {Object.keys(create).filter(f => f !== 'mode').map(f => <label key={f}>{f === 'scope' ? 'Evaluation scope / question' : f}<input required maxLength={f === 'scope' ? 2000 : 200} value={create[f]} onChange={e => setCreate({ ...create, [f]: e.target.value })} /></label>)}<button disabled={!!busy}>Create</button>
    </form></details></section>
    {evaluation && <section className="panel"><h2>{evaluation.customer}</h2><p>{evaluation.facility} · {evaluation.system}</p><p>{evaluation.scope}</p><ol className="stages">{STAGES.map(s => <li key={s} aria-current={s === (review ? 'CUSTOMER REPORT' : run ? 'EVIDENCE' : evaluation.stage) ? 'step' : undefined}>{s}</li>)}</ol><h3>Preserved runs</h3>{evaluation.runs.map(r => <div key={r.id}>{action(`${r.status} · ${r.created_at.slice(0, 19)}`, async () => { const saved = await get(`/runs/${r.id}`); setRun(saved); setReview(saved.reviews?.[0] || null); setReviewed(false); })}</div>)}</section>}
    </aside><main>{!evaluation ? <section className="panel"><h2>Start with an evaluation</h2><p>Create or select a customer evaluation, then upload historical telemetry.</p></section> : <>
    <section className="panel"><h2>1. Receive historical data</h2><p>UTF-8 CSV, TSV or JSON row arrays · 10 MiB, 10,000 rows, 64 columns maximum. One system per evaluation. Original bytes are preserved.</p>{evaluation.mode === 'paired' && <><p>Upload reference → upload comparison → validate both → confirm shared mapping → run comparison → evidence → report.</p><label>Upload reference<input type="file" accept=".csv,.tsv,.json" onChange={e => { const file = e.target.files[0]; if (file) act('Preserving reference', async () => { await upload(evaluation.id, file, 'reference'); await select(evaluation.id); }); e.target.value = ''; }} /></label>{evaluation.reference_source && <><p>Reference: {evaluation.reference_source.filename} · SHA-256 <code>{evaluation.reference_source.sha256}</code></p>{action('Download reference original', () => download(`/sources/${evaluation.reference_source.id}/original`, evaluation.reference_source.filename))}</>}</>}
    <label>{evaluation.mode === 'paired' ? 'Upload comparison' : 'Upload dataset'}<input type="file" accept=".csv,.tsv,.json" disabled={!!busy} onChange={e => { const file = e.target.files[0]; if (file) act('Preserving source', async () => { await upload(evaluation.id, file); await select(evaluation.id); }); e.target.value = ''; }} /></label>
    {evaluation.source && <><p>{evaluation.source.filename} · SHA-256 <code>{evaluation.source.sha256}</code></p>{action('Download original', () => download(`/sources/${evaluation.source.id}/original`, evaluation.source.filename))}<details><summary>First 8 source rows</summary><Json value={evaluation.source.preview} /></details></>}
    </section>
    {evaluation.mode === 'paired' && evaluation.reference_source && <section className="panel"><h2>2. Validate reference</h2><label>Reference timestamp column<select value={referenceTime.timestamp_column} onChange={e => { setReferenceTime({ ...referenceTime, timestamp_column: e.target.value }); setApproved(false); setPreview(null); }}><option value="">Choose explicitly…</option>{evaluation.reference_source.columns.map(c => <option key={c}>{c}</option>)}</select></label><label>Reference timestamp format<select value={referenceTime.timestamp_mode} onChange={e => { setReferenceTime({ ...referenceTime, timestamp_mode: e.target.value }); setApproved(false); setPreview(null); }}><option value="iso">ISO with timezone</option><option value="epoch_seconds">Unix seconds</option><option value="epoch_milliseconds">Unix milliseconds</option></select></label>{action('Validate reference', async () => { await post(`${root}/validate?role=reference`, referenceTime); await select(evaluation.id); }, !referenceTime.timestamp_column)}{evaluation.reference_validation && <Json value={evaluation.reference_validation} />}</section>}
    {evaluation.source && <section className="panel"><h2>2. Validate comparison / dataset timestamps and data quality</h2><div className="fields"><label>Timestamp column<select value={time.timestamp_column} onChange={e => { setTime({ ...time, timestamp_column: e.target.value }); setApproved(false); setPreview(null); }}><option value="">Choose explicitly…</option>{evaluation.source.columns.map(c => <option key={c}>{c}</option>)}</select></label><label>Timestamp format<select value={time.timestamp_mode} onChange={e => { setTime({ ...time, timestamp_mode: e.target.value }); setApproved(false); setPreview(null); }}><option value="iso">ISO with timezone</option><option value="epoch_seconds">Unix seconds</option><option value="epoch_milliseconds">Unix milliseconds</option></select></label></div>
    {action('Validate', async () => { const v = await post(`${root}/validate`, time); await refresh(evaluation.id); setMapping({ ...EMPTY, signals: v.signals.map(s => ({ column: s.column, include: false, meaning: '', unit: '', reason: '' })) }); setPreview(null); setApproved(false); setRun(null); setReview(null); }, !time.timestamp_column)}
    {evaluation.validation && <><p>{evaluation.validation.row_count} rows · {evaluation.validation.start} → {evaluation.validation.end}</p><p>{evaluation.validation.eligible_timestamps ? 'Timestamps eligible for mapping.' : 'Timestamp corrections required before analysis.'}</p><ul>{evaluation.validation.warnings.map(w => <li key={w}>{w}</li>)}</ul><details><summary>Per-signal quality</summary><Json value={evaluation.validation.signals} /></details></>}
    </section>}
    {evaluation.validation?.eligible_timestamps && (evaluation.mode !== 'paired' || evaluation.reference_validation?.eligible_timestamps) && <section className="panel"><h2>3. Confirm signals and system context</h2><p>Include source telemetry with confirmed meaning. Leave unsupplied units blank. Exclude identifiers, failure labels and unrelated signals with a reason.</p><div className="table-scroll"><table><thead><tr><th>Include</th><th>Source signal</th><th>Confirmed meaning</th><th>Unit</th><th>Exclusion reason</th></tr></thead><tbody>{mapping.signals.map((s, i) => <tr key={s.column}><td><input type="checkbox" aria-label={`Include ${s.column}`} checked={s.include} onChange={e => editSignal(i, 'include', e.target.checked)} /></td><td>{s.column}</td>{['meaning', 'unit', 'reason'].map(f => <td key={f}><input aria-label={`${s.column} ${f}`} value={s[f]} onChange={e => editSignal(i, f, e.target.value)} /></td>)}</tr>)}</tbody></table></div>
    <label>Supplied system context and known limitations<textarea rows="3" value={mapping.context} onChange={e => edit({ ...mapping, context: e.target.value })} placeholder="System boundary, operating context, known interventions, and what is unknown. Recorded context is not a causal prior." /></label><div className="fields">{(evaluation.mode === 'paired' ? [] : ['start', 'end']).map(f => <label key={f}>Optional {f} (ISO with timezone)<input value={mapping[f]} onChange={e => edit({ ...mapping, [f]: e.target.value })} placeholder="Full source period if blank" /></label>)}</div>
    {evaluation.mode === 'paired' ? <><p>Both complete periods use this shared mapping. Identical signal columns and explicitly supplied matching units are required. Paired analysis uses full authoritative supplied-reference SII, retaining governed findings, timing, persistence and limitations as supplied.</p><label><input type="checkbox" checked={!!mapping.pair_confirmed} onChange={e => edit({ ...mapping, pair_confirmed: e.target.checked })} />I verified both sources describe the same physical system and signal identities, meanings and units. This inclusion/exclusion mapping applies to both; outcome labels are excluded.</label></> : <p>Neraium-1.0 selects baseline/comparison windows within this interval. History is not presumed healthy. No cross-run memory or engineering priors are enabled.</p>}
    {action('Preview mappings', async () => { setPreview(await post(`${root}/mapping-preview`, mapping)); setApproved(false); await refresh(evaluation.id); }, !mapping.signals.length)}
    {preview && <><h3>Authority classification preview</h3>{preview.catalog.reference && <details><summary>Reference classifications (review both)</summary><Json value={preview.catalog.reference} /></details>}<p>Confirm inferred analysis categories. If incorrect, revise the meaning or exclude the signal. Units are supplied by you.</p><div className="table-scroll"><table><thead><tr><th>Signal</th><th>Analysis category</th><th>Unit</th><th>Reason</th></tr></thead><tbody>{Object.entries(preview.catalog.comparison || preview.catalog).filter(([k]) => k !== 'timestamp').map(([k, v]) => <tr key={k}><td>{k}</td><td>{v.telemetry_category}</td><td>{v.engineering_units || 'Unknown'}</td><td>{v.telemetry_classification?.reason}</td></tr>)}</tbody></table></div>{action(approved ? 'Mapping approved' : 'Confirm classifications, units, context and window policy', async () => { await post(`${root}/approve-mapping`, { preview_id: preview.id, confirmed: true }); setApproved(true); await refresh(evaluation.id); }, approved)}</>}
    </section>}
    {approved && <section className="panel"><h2>4. Authoritative analysis</h2><p>Up to 120 seconds. A completed run may have no findings or limited evidence. Failures are preserved without substituted results.</p>{action('Run historical analysis', async () => { const r = await post(`${root}/runs`); const saved = await get(`/runs/${r.id}`); setRun(saved); setReview(saved.reviews?.[0] || null); setReviewed(false); await refresh(evaluation.id); })}</section>}
    {run && <section className="panel"><h2>5. Results and evidence</h2><p>Run <code>{run.id}</code> · <strong>{run.status}</strong> · source {run.source.filename}</p>{run.reference_source && <><p>Reference: {run.reference_source.filename} · {run.reference_validation.start} → {run.reference_validation.end} · SHA-256 <code>{run.reference_source.sha256}</code></p><p>Comparison SHA-256 <code>{run.source.sha256}</code></p></>}{run.error && <p className="error">{run.error}</p>}{run.status === 'running' && <p>No terminal result stored. If the server was interrupted, start a new run; this record is not usable evidence.</p>}
    {run.response && <><p>Execution status is not equipment health. No finding does not mean stable.</p><p>Window: {run.input.rows[0].timestamp} → {run.input.rows[run.input.rows.length - 1].timestamp}</p>{Object.entries(run.evidence_sections).map(([label, v]) => <details key={label}><summary>{label}</summary>{Array.isArray(v) && !v.length ? <p>No entries supplied by the authoritative engine.</p> : <Json value={v} />}</details>)}<details><summary>Full authoritative result and module limitations</summary><Json value={run.response.result} /></details></>}
    {action('Download evidence JSON', () => download(`/runs/${run.id}/evidence`, `neraium-evidence-${run.id}.json`))}
    {['complete', 'limited'].includes(run.status) && <><h2>6. Review and customer report</h2><label>Reviewer name<input value={reviewer} onChange={e => setReviewer(e.target.value)} /></label><label><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)} />I reviewed this run's scope, source, mapping, results and evidence limitations.</label>{action('Record review', async () => { setReview(await post(`/runs/${run.id}/reviews`, { reviewer, evidence_reviewed: true })); await refresh(evaluation.id); }, !reviewed || !reviewer.trim())}
    {review && <>{action('Download printable customer report', () => download(`/reviews/${review.id}/report`, `neraium-report-${run.id}.html`))}<p>Open the HTML to print/save as PDF. Deliver with evidence JSON. The report uses engine evidence only, without generated diagnosis or consequence estimates.</p></>}</>}
    </section>}
    </>}</main></div></fieldset></>}
  </div>;
}
